[tool.poetry]
name = "strawberry-graphql-django"
packages = [{ include = "strawberry_django" }]
version = "0.3.1"
description = "Strawberry GraphQL Django extension"
authors = ["Lauri Hintsala <lauri.hintsala@verkkopaja.fi>"]
repository = "https://github.com/strawberry-graphql/strawberry-graphql-django"
license = "MIT"
readme = "README.md"
keywords = ["graphql", "api", "django"]
classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Framework :: Django",
  "Framework :: Django :: 3.2",
  "Framework :: Django :: 4.0",
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
Django = ">=3.0"
strawberry-graphql = ">=0.109.0"

# docs-deps
mkdocs = { version = "^1.3.0", optional = true}
mkdocs-markdownextradata-plugin = {version = "^0.2.5", optional = true}
mkdocs-material = {version = "^8.3.8", optional = true}
mkdocs-minify-plugin =  {version = "^0.5.0", optional = true}
pymdown-extensions = {version = "^9.5", optional = true}
markdown = {version = "^3.3.7", optional = true}


[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
pytest-django = "^4.1.0"
pytest-pythonpath = "^0.7.3"
pytest-watch = "^4.2.0"
django-filter = "^2.4.0"
pytest-mock = "^3.5.1"


[tool.poetry.extras]
docs = [
    "mkdocs",
    "mkdocs-markdownextradata-plugin",
    "mkdocs-material",
    "mkdocs-minify-plugin",
    "pymdown-extensions",
    "markdown",
]


[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
indent = 4
combine_star = true
combine_as_imports = true
lines_after_imports = 2

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.django_settings"
testpaths = ["tests"]
filterwarnings = "ignore:.*is deprecated.*:DeprecationWarning"
