# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, "v*"]
  pull_request:
    branches: [main, "v*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  geotests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies to test geofields on sqlite
        run: sudo apt-get install binutils gdal-bin libproj-dev libsqlite3-mod-spatialite

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest

  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest
